language: c
sudo: false

env:
  global:
  - PRETTYNAME="Ultrasonic Proximity Sensor (HC-SR04, ...)"

before_install:
- source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)

script:
- build_main_platforms
